### ISSUE TITLE
같은 코드로 ./postlist/* 와 ./ 의 작동이 다른 문제.

### ISSUE THREAD

**Issue by thhj153** [thhj153/gowebfinal#13]
http://155.230.193.223:4001/postlist/60ba331a5f60a00aa4b18962 에서

<div class="post-preview">
                <a href=**"/post/60ba3c11b5469a30e4513a5b**">
                    <h2 class="post-title"> 자유게시판 첫 글 </h2>
                </a>
                <p class="post-meta">
                _By: <a href="#"></a> <br>_
                Date: 2021-06-05
                </p>
            </div>

http://155.230.193.223:4001/ 에서
<div class="post-preview">
                <a href="**/post/60ba3c11b5469a30e4513a5b**">
                    <h2 class="post-title"> 자유게시판 첫 글 </h2>
                </a>
                <p class="post-meta">
                _By: <a href="#">pavk</a> <br>_
                Date: 2021-06-05
                </p>
            </div>

Bold 부분이 같음에도 Underline 부분이 다른 문제 발생

**Comment by wnwoghd22** [comment]
이름이 출력되지 않는 문제는 BlogPost의 userid 필드를 실제 User 스키마로 populate해주지 않아서 생긴 문제였습니다.
코드 업데이트 했으니 확인바랍니다.

**Comment by thhj153** [comment]
정상적으로 나타나는 것 확인했습니다.
