### ISSUE TITLE
포스트 관련 문제

### ISSUE THREAD

**Issue by thhj153** [thhj153/gowebfinal#17]
![image](https://user-images.githubusercontent.com/44903440/121048737-06800b80-c7f2-11eb-9738-f85d9543bf9d.png)

            <%/* if (blogpost.userid==userInfo._id.toString() ){ */%>
              <a href="/posts/modify" class="btn btn-primary post" >MODIFY</a>
              <a href="/posts/delete" class="btn btn-primary post" >DELETE</a>
              <%/* } */%>

요기에서 에러가 나네요.

**Comment by wnwoghd22** [comment]
주석처리가 되어 있네요?

그... 다음부터는 이슈에 코드 올릴 때 어떤 파일의 몇 번 째 줄인지 명시해 주세요...

**Comment by thhj153** [comment]
post.ejs line 22 to 24. (작성자명 나타나지 않음)
post.ejs line 64 to 67. 버튼 2개(수정, 삭제 나타나지 않음)
