### ISSUE TITLE
새 계정 생성이 되지 않습니다.

### ISSUE THREAD

**Issue by wnwoghd22** [thhj153/gowebfinal#3]
storeUser.js의 User.create()가 제대로 작동하지 않습니다.
필수로 들어가야 하는 필드 값이 주어지지 않아서인지 계속 register 화면으로 redirect 됩니다.

문제를 해결하려면
User.create 의 첫번째 패러미터로 req.body를 넣는 것이 아니라
User 스키마에 맞춘 새로운 Object를 만들어 넣어볼 필요가 있겠습니다.

혹시 저번에 switch 이하 구문을 삭제한 게 오류의 원인이 아닐지 싶네요.

**Comment by pavk96** [comment]
스키마에 맞게 데이터를 넘겨주지 않은것이 원인이었습니다 해결!
