### ISSUE TITLE
2021. 6. 1 할 일 정리

### ISSUE THREAD

**Issue by thhj153** [thhj153/gowebfinal#7]
ㄱ. 소작업 
 1. 잘못된 행위 "alert 추가"

 ㄴ. 포스트
 2. post 카테고리, 읽기 등급 설정 기능 추가(스키마 포함 수정)
 3. admin; 공지등록 권한
 4. 작성자 글 수정
 5. post ejs 수정
 6. 이미지 없이도 업로드 가능

ㄷ. 카테고리 바
 7. 카테고리 별 모아보기(post 스키마 수정 선행)
 ( 8. 카테고리바 설정 개선 )
 
 ㄹ. 댓글 관련
 9. 댓글
    - 댓글 스키마; post id 물고, post id. 기본적으로 포스트 정리
    - 이미지 검사 지우면 해결

6월 4일까지 완료해봅시다.
하실 내용 댓글 or 디스코드 or 카톡에 적어주세요.

**Comment by thhj153** [comment]
6, 7(문제 발생), 8, 9 이외 완료.

**Comment by wnwoghd22** [comment]
6번, 7번 (이름 표시 문제 해결) 완료

**Comment by thhj153** [comment]
고생하셨습니다.
